resources:
- repo: self

queue:
  name: Hosted VS2017

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: GLFWDotNet.sln
    arguments: '/v:d'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: src/GLFWDotNet/GLFWDotNet.csproj
    buildProperties: 'Configuration=Release;BuildNumber=$(Build.BuildNumber)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: GLFWDotNet'
  inputs:
    artifactName: 'GLFWDotNet'


